# Server settings
server:
  port: 8018

eureka:
  instance:
    hostname: localhost
    #prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eurka: OFF
        discovery: OFF
